config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'menus#new'
  get 'menus/:menu_id/orders', to: "results#order", as: :order
  get 'foods/:food_id/results/:id', to: 'foods#show', as: :results_food_show
  patch 'results/:id/toggle', to: 'results#toggle', as: :toggle_result

  resources :menus, only: [:create] do
    resources :results, only: [:index]
  end

  resources :results, only: [:update]

  resources :foods, only: [:show] do
    resources :favourites, only: [:create]
  end

  resources :favourites, only: [:index, :destroy]
end

app/models/favourite.rb
class Favourite < ApplicationRecord
  belongs_to :user
  belongs_to :food

  validates_uniqueness_of :user_id, scope: :food_id
end

app/controllers/favourites_controller.rb
class FavouritesController < ApplicationController
  def index
    @user = current_user
    if @user.favourited_foods.first.nil?
      @favourited_foods = []
    else
      @favourited_foods = @user.favourited_foods
      @food_images = SearchImagesAndPopularity.call(@user.favourited_foods[0].name)
    end
    @fav = Favourite.where(user_id: current_user)
  end

  def create
    @favourite = Favourite.new
    @favourite.food = Food.find(params[:food_id])
    @favourite.user = current_user
    if @favourite.save!
      @fav = Favourite.where(user_id: current_user)
      respond_to do |format|
        format.html { redirect_to food_path(@favourite.food) }
        format.js
      end
    else # -> REFERENCE 1 (refer to the bottom)
      flash[:alert] = "That food is already added in your favourites."
      render 'index'
    end
  end

  def destroy
    @favourite = Favourite.find(params[:id])
    @food = @favourite.food
    @favourite.delete
    @fav = Favourite.where(user_id: current_user)
    respond_to do |format|
      format.html { redirect_to food_path(@favourite.food) }
      format.js
    end
  end

  private

  def favourite_params
    params.require(:favourite).permit(:user_id, :food_id)
  end
end

# REFERENCES
# 1. This else statement is theoretically required. But it should never be run.
#     Because we don't set POST request in Food#show view when that food is
#     already added. Thus, if you see this else statement run, something wrong
#     with Food#show view or .js file.

app/views/favourites/create.js.erb
function insertNumber(html) {
  const heartIconBottom = document.querySelector('.bottom-icon.heart-bottom');
  heartIconBottom.insertAdjacentHTML("beforeend", html);
}

function insertDeleteLink() {
  const heartIconBody = document.querySelector('.favourite-buttom');
  heartIconBody.innerHTML = '<%= button_to favourite_path(@favourite), method: :delete, remote: true, class: "bottom-icon added" do %><i class="fas fa-heart"></i><% end %>';
}

<% if @fav.length > 0  %>
  insertNumber('<span class="cart-num"><%= @fav.length %></span>');
<% end %>

insertDeleteLink();

app/views/favourites/destroy.js.erb
function insertNumber(html) {
  const heartIconBottom = document.querySelector('.bottom-icon.heart-bottom');
  if (<%= @fav.length %> > 0){
    heartIconBottom.insertAdjacentHTML("beforeend", html);
  } else {
    elem = heartIconBottom.querySelector('.cart-num');
    elem.parentNode.removeChild(elem);
  }
}

function insertCreateLink() {
  const heartIconBody = document.querySelector('.favourite-buttom');
  heartIconBody.innerHTML = '<%= button_to food_favourites_path(@food), method: :post, remote: true, class: "bottom-icon", id: "add-heart" do %><i class="fas fa-heart"></i><% end %>';
}


insertNumber('<span class="cart-num"><%= @fav.length %></span>');
insertCreateLink();

app/views/favourites/index.html.erb
<% content_for :navbar_left do %>
  <% menu = Menu.where(user_id: current_user.id).last %>
  <%= link_to menu_results_path(menu), class: "top-back" do %>
    <i class="fas fa-chevron-left"></i>
  <% end %>
<% end %>
<% content_for :navbar_center do %>
  Favourites
<% end %>
<% content_for :meta_title do %>
  Favourites
<% end %>
<!-- top bar -->
<%= render 'shared/favtopbar' %>
<div id="hello">
  <div class="favourite-container">
    <% counter = 0 %>
    <% @favourited_foods.each do |favourited_food| %>
      <div class="content">
        <div class="img-fav">
          <%= link_to food_path(favourited_food), class: "link-food" do %>
            <% if favourited_food.images.nil? %>
              <%= image_tag(@food_images[:image_paths][0], class: "img") %>
            <% else %>
              <%= image_tag(favourited_food.images[0], class: "img") %>
            <% end %>
          <% end %>
        </div>


          <%= link_to food_path(favourited_food.id), class: "text-content-a" do %>
          <div class="text-content">
            <dl>
              <dt><%= favourited_food.en %></dt>
              <dd class="search-food-desc"><%= favourited_food.name %></dd>
            </dl>
            <div class="show-page"><i class="fas fa-angle-right "></i></div>
          </div>
          <% end %>

        </div>
      <% end %>

  </div>
</div>
<!-- // hello -->
<%= render 'shared/favbotbar' %>