config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'menus#new'
  get 'menus/:menu_id/orders', to: "results#order", as: :order
  get 'foods/:food_id/results/:id', to: 'foods#show', as: :results_food_show
  patch 'results/:id/toggle', to: 'results#toggle', as: :toggle_result

  resources :menus, only: [:create] do
    resources :results, only: [:index]
  end

  resources :results, only: [:update]

  resources :foods, only: [:show] do
    resources :favourites, only: [:create]
  end

  resources :favourites, only: [:index, :destroy]
end

app/views/shared/_botnavbar.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm bot-bar">
      <%= link_to root_path, class: "nav-icon" do %>
        <i class="fas fa-camera"></i>
      <% end %>

      <%= link_to root_path, class: "nav-icon" do %>
        <i class="fas fa-heart"></i>
      <% end %>

      <%= link_to root_path, class: "nav-icon" do %>
        <i class="fas fa-shopping-cart"></i>
      <% end %>

      <%= link_to root_path, class: "nav-icon" do %>
        <i class="fas fa-clock"></i>
      <% end %>

      <%= link_to root_path, class: "nav-icon" do %>
        <i class="fas fa-user"></i>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_explanation.html.erb
<div class="explanation-title">
  <h2>Miru</h2>
  <p>Miru is the greatest app that allows most accurate translation of any food related menus and their visualization. Eat like the local.</p>
</div>

<h3>Project Team</h2>
<div class="row">
  <div class="card-team col-sm-3 col-md-1">
    <%= image_tag "https://avatars1.githubusercontent.com/u/42114758?v=4" , class: "img-circle avatar" %>
    <%= link_to "https://github.com/NinthAutumn" do %>
      <p>Arif Iwamoto</p>
    <% end %>
  </div>

  <div class="card-team col-sm-3 col-md-1">
    <%= image_tag "https://avatars1.githubusercontent.com/u/14194991?v=4" , class: "img-circle avatar" %>
    <%= link_to "https://github.com/kiuuk" do %>
      <p>Kiwook Ha</p>
    <% end %>
  </div>

  <div class="card-team col-sm-3 col-md-1">
    <%= image_tag "https://avatars0.githubusercontent.com/u/42990872?v=4" , class: "img-circle avatar" %>
      <%= link_to "https://github.com/grunhub" do %>
        <p>Raymond Cheong</p>
      <% end %>
  </div>

  <div class="card-team col-sm-3 col-md-1">
    <%= image_tag "https://avatars1.githubusercontent.com/u/42410688?v=4" , class: "img-circle avatar" %>
    <%= link_to "https://yutafujii.herokuapp.com/" do %>
      <p>Yuta Fujii</p>
    <% end %>
  </div>
</div>

app/views/shared/_favbotbar.html.erb
<div class="container" id="common-bottom">
  <div class="row">
    <!-- camera -->
    <%= link_to root_path, class: "bottom-icon" do %>
      <i class="fas fa-camera"></i>
    <% end %>
    <!-- bag -->
    <% if @menu %>
      <% orders = Result.where("results.order > ?", 0).where(menu_id: @menu.id).sum("order") %>
      <%= link_to order_path(@menu), class: "bottom-icon cart-bottom" do %>
        <i class="fas fa-shopping-bag"></i>
        <!-- if cart is empty add 'empty' class -->
        <% if orders > 0  %>
          <span class="cart-num"><%= orders %></span>
        <% end %>
        <!-- <span class="cart-num">3</span> -->
      <% end %>
    <% else %>
      <a href="#" class="bottom-icon"><i class="fas fa-shopping-bag hidden"></i></a>
    <% end %>
    <!-- heart -->
      <%= link_to favourites_path, class: "bottom-icon heart-bottom" do %>
        <i class="fas fa-heart"></i>
          <% if @fav.length > 0  %>
            <span class="cart-num"><%= @fav.length %></span>
          <% end %>
      <% end %>
  </div>
</div>

app/views/shared/_favtopbar.html.erb
<div class="container" id="common-top">
  <div class="row">
    <%= content_for :navbar_left %>
    <h1><%= content_for :navbar_center %></h1>
    <%= content_for :navbar_right %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_resultsbotbar.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm bot-bar">
      <%= link_to root_path, class: "nav-icon" do %>
        <i class="fas fa-camera"></i>
      <% end %>
      <%= link_to 'See Order List', root_path, class: "order-btn" %>
      <%= link_to root_path, class: "nav-icon" do %>
        <i class="fas fa-heart"></i>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_resultstopbar.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm top-bar">
      <%= link_to root_path, class: "nav-icon" do %>
        <i class="fas fa-angle-left"></i>
      <% end %>
      <h2 class="heading">Results</h2>
      <%= link_to root_path, class: "nav-icon" do %>
        <i class="fas fa-sort-amount-down"></i>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_topnavbar.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm top-bar">
      <%= link_to root_path, class: "nav-icon" do %>
        <i class="fas fa-angle-left"></i>
      <% end %>
      <h2 class="heading">Results</h2>
      <%= link_to root_path, class: "nav-icon" do %>
        <i class="fas fa-sort-amount-down"></i>
      <% end %>
    </div>
  </div>
</div>