config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'menus#new'
  get 'menus/:menu_id/orders', to: "results#order", as: :order
  get 'foods/:food_id/results/:id', to: 'foods#show', as: :results_food_show
  patch 'results/:id/toggle', to: 'results#toggle', as: :toggle_result

  resources :menus, only: [:create] do
    resources :results, only: [:index]
  end

  resources :results, only: [:update]

  resources :foods, only: [:show] do
    resources :favourites, only: [:create]
  end

  resources :favourites, only: [:index, :destroy]
end

app/models/result.rb
class Result < ApplicationRecord
  belongs_to :food
  belongs_to :menu
end

app/controllers/results_controller.rb
class ResultsController < ApplicationController
  def index
    # TODO: return all results with image paths
    # set the instances
    # search images for each food

    @results = Result.where(menu_id: params[:menu_id])
    search_image_for_each_food(@results)
    @fav = Favourite.where(user_id: current_user)
    @menu = Menu.find(params[:menu_id]) #footer favourite number
    @all = @results.to_json
    @sort_name = @results.includes(:food).order("foods.name")
    @sort_popularity = @results.includes(:food).order("foods.popularity")

  end

  def order
    @orders = Result.where("results.order > ?", 0).where(menu_id: params[:menu_id].to_i)
    @menu = Menu.find(params[:menu_id])
    if @orders.first.nil? # If no orders made
      @food_title = ""
      @food_summary = ""
    else
      @food_title = @orders.first.food.name
      @food_summary = @orders.first.food.en
    end
    @fav = Favourite.where(user_id: current_user) #footer favourite number
  end

  # for the order page/ + and - icon
  def update
    @result = Result.find(params[:id])
    if params[:button] == "increase"
      @result.order += 1
    elsif params[:button] == "decrease"
      @result.order -= 1
    end
    @result.save!
    @order_total = Result.where("results.order > ?", 0).where(menu_id: @result.menu.id).sum("order")
    respond_to do |format|
      format.js
    end
  end

  # for the result#index page/ check icon
  def toggle
    @result = Result.find(params[:id])
    @result.order = @result.order.zero? ? 1 : 0
    @result.save!
    @order_total = Result.where("results.order > ?", 0).where(menu_id: @result.menu.id).sum("order")
    respond_to do |format|
      format.js
    end
  end

  private

  def search_image_for_each_food(results)
    # boost threads to increase performance
    # pool = Concurrent::FixedThreadPool.new(10)
    # completed = []

    translation_of_meal = Language.find_by(code: results.first.lang)&.meal_is # -> REFERENCE 1 (refer to the bottom)
    results.each do |result|
      # pool.post do
        # ==========================================
        # if result.food.images.nil?
        #   result.food.images = [Food::SAMPLE_IMAGES.sample]
        #   result.food.save!
        # end
        # ------------------------------------------
        if result.food.en.nil?
          result.food.en = Translate.call(result.food.name)
          result.food.save!
        end
        if result.food.images.nil?
          keyword = "#{result.food.name}+#{translation_of_meal}"
          attributes = SearchImagesAndPopularity.call(keyword)
          result.food.popularity = [999999999, attributes[:popularity]].min
          result.food.images = attributes[:image_paths]
          result.food.save!
        end
        # ==========================================
        # completed << 1
      # end
    end
    # temporary measure: wait_for_termination does not work well
    # sleep(0.1) unless completed.count == results.count
    # pool.shutdown
    # pool.wait_for_termination
  end
end

# REFERENCES
# 1. Here, we get the string of 'meal' translated to the language of the menu.
#     This variable is used for creating keyword which we pass to the API.
#     The reason for this is to improve the relevance of the result images.
#     For example, Japanese menu has lot of fishes which really is 'sashimi',
#     but if you put those words API returns the fish itself not the meal.
#     There are other possibilities as an additional keyword to search with:
#       - food(english)
#       - meal(english)
#       - 'food'(translated to that lang)
#     However we feel 'meal'(translated) is the best performer.

app/views/results/_order_list_banner.html.erb
<% @orders.each_with_index do |order, index| %>
  <div class="card-order-list <%= "active" if index == 0 %>">
    <%= cl_image_tag(order.food.images[0], class: "img-circle list-#{index} img-top" ) %>
    <div class="triangle-wrap"><i class="fas fa-sort-up"></i></div>
  </div>
<% end %>

app/views/results/_order_list_body.html.erb
<% @orders.each_with_index do |order, index| %>
  <div class="card-result-body <%= "list-#{index}" %> <%= "hidden" unless index == 0 %>">
    <div class="card-result-body-img"><%= cl_image_tag(order.food.images[0], class: "img-circle result-center image-order" ) %></div>
    <!-- desc -->
    <div class="food-description">
      <h2><%= order.food.name %></h2>
      <h3><%= order.food.en %></h3>
    </div>
    <!-- quantity -->
    <div class="quantity">
      <%= simple_form_for order,remote: true do |f| %>
        <%= f.input :order, as: :hidden %>
        <%= f.button :button, value: "decrease", class: "decrease", title: "Decrease Quantity" do %>
          <i class="fas fa-minus-circle"></i>
        <% end %>
      <% end %>
      <input type="text" class="quantity-amount total" name="" value="<%= order.order %>" />
  <%= simple_form_for order,remote: true do |f| %>
    <%= f.input :order, as: :hidden %>
    <%= f.button :button, value: "increase", class: "increase", title: "Increase Quantity" do %>
      <i class="fas fa-plus-circle"></i>
    <% end %>
  <% end %>
</div>
</div>
<% end %>

app/views/results/_order_list_summary.html.erb
<div class="order-list-summary">
  <table>
    <thead>
      <tr>
        <th>MENUS</th>
        <th>QUANTITY</th>
      </tr>
    </thead>
    <tbody>
      <% @orders.each_with_index do |order, index| %>
        <tr>
          <!-- need modifying with @food_title -->
          <td clas="not-big"><%= order.food.name %><span class="english"> (<%= order.food.en %>)</span></td>
          <td class="<%= "list-#{index} text-center bold" %>"></td>
        </tr>
      <% end %>
    </tbody>
  </div>

app/views/results/index.html.erb
<% content_for :meta_title do %>
  Results
<% end %>
<% content_for :navbar_left do %>
  <%= link_to request.referer, class: "top-back" do %>
    <i class="fas fa-chevron-left"></i>
  <% end %>
<% end %>
<% content_for :navbar_center do %>
  Result
<% end %>
<% content_for :navbar_right do %>
  <a id="modal-btn"><i class="fas fa-question-circle"></i></a>
<% end %>

<%= render 'shared/favtopbar' %>
<!-- body -->
<div id="hello">
  <div class="search-container" >
    <% @sort_popularity.each do |result| %>
      <div class="content" id="<%= result.food_id %>">
        <!-- overlay -->
        <div onclick="imageClicked(<%= result.id %>, <%= result.food_id%> )" class="img-div"  >
          <%= link_to toggle_result_path(result), method: :patch, remote: true do %>
            <div class="overlay not-clicked" id="<%= result.id %>">
              <div class="overlay-container">
                <div class="icons">
                  <%= image_tag "check.png" %>
                </div>
              </div>
            </div>
            <%= cl_image_tag(result.food.images[0], class: "img") %>
          <% end %>
        </div>
        <!-- list items -->
        <%= link_to results_food_show_path(result.food_id, result), class: "text-content-a" do %>
        <div class="text-content">
          <dl>
            <dt><%= result.food.en %></dt>
            <dd class="search-food-desc"><%= result.food.name %></dd>
          </dl>
          <div class="show-page"><i class="fas fa-angle-right "></i></div>
        </div>
        <% end %>
      </div><!-- content -->
    <% end %>
  </div><!-- // search-container -->
</div><!-- // hello -->

<%= render 'shared/favbotbar' %>

<!-- modal -->
<div id="my-modal" class="modal">
  <div class="modal-content up">
    <div class="modal-body">
      <span class="close"></span>
      <i class="fas fa-arrow-left"></i>
      <p>Tap on the pic<br> to order!</p>
    </div>
  </div>
  <div class="modal-content down">
    <div class="modal-body">
      <span class="close"></span>
      <p>Tap on the icon below to confirm your order</p>
      <i class="fas fa-arrow-down"></i>
    </div>
  </div>
</div>

<script>
  function imageClicked(num, foodname){
      let image = document.getElementById(num);
      let textImage = document.getElementById(foodname);
      image.classList.add('clicked');
      image.classList.remove("not-clicked");
      textImage.classList.add("some");
    }
    var see_ordered = <%= raw @all %>;
    see_ordered.forEach((result)=>{
      if(result.order){
        imageClicked(result.id, result.food_id);
      }
    });
</script>
<script>
  var clicked = false;
  function imageClicked(num, foodname){
      const image = document.getElementById(num);
      const textImage = document.getElementById(foodname);
      if (image.classList.contains('clicked')) {
        image.classList.remove('clicked');
        image.classList.add("not-clicked");
        textImage.classList.remove("some");
      } else {
        image.classList.add('clicked');
        image.classList.remove("not-clicked");
        textImage.classList.add("some");
      }
  }
</script>
<script>
  // Get DOM Elements
  const modal = document.querySelector('#my-modal');
  const modalBtn = document.querySelector('#modal-btn');
  const closeBtn = document.querySelector('.close');

  // Events
  modalBtn.addEventListener('click', openModal);
  closeBtn.addEventListener('click', closeModal);
  modal.addEventListener('click', outsideClick);

  // Open
  function openModal() {
    modal.style.display = 'block';
  }

  // Close
  function closeModal() {
    modal.style.display = 'none';
  }

  // Close If Outside Click
  function outsideClick(e) {
    if (e.target == modal) {
      modal.style.display = 'none';
    }
  }
</script>

app/views/results/order.html.erb
<!-- title for navbar -->
<% content_for :meta_title do %>
  Order List
<% end %>
<% content_for :navbar_left do %>
  <%= link_to menu_results_path(@menu), class: "top-back" do %>
    <i class="fas fa-chevron-left"></i>
  <% end %>
<% end %>
<% content_for :navbar_center do %>
  ORDER
<% end %>

<!-- NEW top bar -->
<%= render 'shared/favtopbar' %>
<div class="container-body">
  <div class="result-top-wrap">
    <div class="banner result-top">
      <%= render 'order_list_banner', object: [@orders] %>
    </div>
  </div>
  <div class="container order-body">
    <%= render 'order_list_body', object: [@orders, @food_title] %>
  </div>
  <%= render 'order_list_summary', object: [@orders, @food_title] %>
</div>
<!-- NEW footer -->
<%= render 'shared/favbotbar' %>
<%= javascript_pack_tag 'results/order' %>

<script>
  $(document).ready(function() {
    var thumwrap = $('.result-top');
    var thumlist = $('.card-order-list').length;
    var thumwidth = thumlist * 88;
    $(thumwrap).css({"min-width": "375px", "width": thumwidth});
});
</script>

app/views/results/toggle.js.erb
function refreshOrderNum(html) {
  const cartIconBottom = document.querySelector('.bottom-icon.cart-bottom');
  if (<%= @order_total %> > 0){
    cartIconBottom.insertAdjacentHTML("beforeend", html);
  } else {
    elem = cartIconBottom.querySelector('.cart-num');
    elem.parentNode.removeChild(elem);
  }
}

refreshOrderNum('<span class="cart-num"><%= @order_total %></span>');

app/views/results/update.js.erb
function refreshOrderNum(html) {
  const cartIconBottom = document.querySelector('.bottom-icon.cart-bottom');
  if (<%= @order_total %> > 0){
    cartIconBottom.insertAdjacentHTML("beforeend", html);
  } else {
    elem = cartIconBottom.querySelector('.cart-num');
    elem.parentNode.removeChild(elem);
  }
}

refreshOrderNum('<span class="cart-num"><%= @order_total %></span>');